export * from './Header'
export * from './Banner'
export * from './Contas'
export * from './Plataformas'
export * from './ProductStore'
export * from './Ad'
export * from './KeyStore'
export * from './Footer'
